spring:
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/${db.schema}?createDatabaseIfNotExist=true
    username: ${db.username}
    password: ${db.password}

  jpa:
    show-sql: true
    hibernate:
      dll-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

db:
  host: localhost
  schema: challenger
  username: root
  password: root
  port: 3306
